name: .NET Core

on:
  push:
    branches: [ v7build ]
  pull_request:
    branches: [ v7build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
          
    - name: Install Dependencies
      run: dotnet restore
      
  in-mem-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Test
        run: dotnet test ./tests/MassTransit.Tests/MassTransit.Tests.csproj --no-restore --verbosity normal
